### ISSUE TITLE
no validation ground truth

### ISSUE THREAD

**Issue by ugtony** [metalbubble/places_devkit#1]
Hi, 
The Readme says the classification ground truth of the validation images is in data/places365_val.txt, but there is no such file. Could you check that? Thanks.

**Comment by zhoubolei** [comment]
Please read the Readme carefully to get the link to download the file. Thanks.

**Comment by erogol** [comment]
The classification ground truth of the validation images is in data/places365_val.txt,

It says but no data on the path am I wrong ?

**Comment by zhoubolei** [comment]
"Note: Please first download the image list and annotations for Places365-Standard and the image list and annotations for Place365-Challenge, and decompress the files in the data folder."
