### ISSUE TITLE
Where is the file, "data/places365_val.txt" ??

### ISSUE THREAD

**Issue by taey16** [metalbubble/places_devkit#2]
@metalbubble 
Hi, 
We are preparing for the challenge.
We first downloaded Places2-Challenge dataset and places_devkit, however we didn't find any label information for the validation set.
Please, give us some comments.

Thanks

taey16

**Comment by zhoubolei** [comment]
See the HIGHLIGHT in the readme. Thanks. 'Note: Please first download the image list and annotations for Places365-Standard and the image list and annotations for Place365-Challenge, and decompress the files in the data folder.'

**Comment by zhoubolei** [comment]
Please see the newly added shell file.
https://github.com/metalbubble/places_devkit/blob/master/data/download_data.sh
